export const AUTHOR = 'Author';
export const BOOK_BUDDY = 'Book Buddy';
export const BOOK_NOT_EMBEDED = 'Book Not Embeded';
export const CANVAS_STILL_LOADING = 'Canvas is still loading...';
export const DOWNLOAD_LINKS = 'Download links:';
export const EPUB = 'epub';
export const PDF = 'pdf';
export const LANGUAGE = 'Language:';
export const LOGIN_FAILED = 'Login Failed';
export const NOT_AVAILABLE = 'n/a';
export const PAGE_COUNT = 'Page Count:';
export const PUBLISHER = 'Publisher:';
export const PUBLISHED_DATE = 'Published Date:';
export const RATING_COUNT = 'Rating Count:';
export const SEARCH_PLACEHOLDER = 'Search for an author...';
export const SCRIPT_NOT_LOADED = 'Script not loaded';
export const TITLE = 'Title:';
export const WELCOME_TEXT =
  'Welcome to Book Buddy, Your online book author search engine';
